---
abstract: 'Flashcard set with the basic 46 japanese hiragana'
author:
  - 'Christian Walde <mithaldu@yahoo.de>'
build_requires:
  Quiz::Flashcards: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Quiz-Flashcards-Sets-Hiragana-Romaji_Simple
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
